const parser = require('./dist/parser.cjs'); // parser generated by pegjs --trace
const Tracer = require('pegjs-backtrace');

const fs = require('fs');

let rawdata = fs.readFileSync('test/conformance.sol', 'utf-8');


let success = process.argv[2] || "1 / 1";
let failure = process.argv[3] || "oh no";

let tracerOptions = [
  // {
  //   showTrace: true,
  //   hiddenPaths: ["*/primary/*", "*/ws/*"],
  //   showFullPath: true,
  //   showSource: true
  // },
  {
    hiddenPaths: ["*/ws/*"],
    showFullPath: true,
    showSource: true,
    matchesNode: function(node, options = {}) {
      if (options.backtrace) {
        return true;
      }

      if (options.grep && !node.rule.includes(options.grep)) {
        return false;
      }

      if (options.nodeType && options.nodeType != node.type) {
        return false;
      }

      return true;
    }
  }
]

let matchesOptions = [
  {},
  { grep: 'integer' },
  { nodeType: 'rule.match', grep: 'integer' },
]

let solidity = parser.parse( rawdata);
tracerOptions.forEach((tracerOptions) => {
  matchesOptions.forEach((matchesOptions) => {
    let tracerSuccess = new Tracer(success, tracerOptions);
    let tracerFailure = new Tracer(failure, tracerOptions);

    let result = parser.parse(success, { tracer: tracerSuccess });

    console.log(`\n   SUCCESS FOR ${success} \n`);
    console.log(`\n  tracer options: ${solidity(tracerOptions)}\n`)
    console.log(`\n== getParseTreeString(${solidity(matchesOptions)}) ==\n`)
    console.log(tracerSuccess.getParseTreeString(matchesOptions));
    console.log("\n== result ==\n")
    console.log(result)

    try {
      parser.parse(failure, { tracer: tracerFailure });
    } catch (e) {
      console.log(`\n   FAILURE FOR ${failure} \n`);
      console.log(`\n  tracer options: ${solidity(tracerOptions)}\n`)
      console.log(`\n== getBacktraceString(${solidity(matchesOptions)}) ==\n`)
      console.log(tracerFailure.getBacktraceString(matchesOptions));
      console.log("\n== error message ==\n")
      console.log(e.message);
    }
  })
})